### ISSUE TITLE
[New Feature]  enable purgeaudit

### ISSUE THREAD

**Issue by teimyBr** [steadforce/harbor-day2-operator#4]
[New Feature]  enable purgeaudit

This helps that the harbor db not get over filled and keeps clean.  

API Call:  "/api/v2.0/system/purgeaudit/schedule"

Configuration options should be:

```
purgeauditschedule:
    parameters:
      audit_retention_hour: 720
      dry_run: false
      include_operations: create,delete,pull
    schedule:
      cron: "0 0 0 * * *"
      type: Daily
```
